version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/yourdbname

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '5000:5000'
    depends_on:
      - backend

volumes:
  mongo-data: